groups:
- name: service-alerts
  rules:
  - alert: HighErrorRate
    expr: |
      (rate(http_server_requests_seconds_count{status!~"2.."}[1m])
      /
      rate(http_server_requests_seconds_count[1m])) > 0.1
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High HTTP error rate detected"
      description: "Error rate > 10% over 1m window"
