{
 "title": "HTTP Service Metrics",
 "tags": [
  "http",
  "metrics",
  "prometheus"
 ],
 "panels": [
  {
   "title": "Availability (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (env, app) (rate(http_server_requests_seconds_count{status=~\"2..\"}[5m]))\r\n/\r\nsum by (env, app) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{env}}:{{app}}"
    }
   ]
  },
  {
   "title": "5xx Error Rate (errors/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (env, app) (rate(http_server_requests_seconds_count{status!~\"2..\"}[5m]))",
     "legendFormat": "{{env}}:{{app}}"
    }
   ]
  },
  {
   "title": "Average Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (app, env) (rate(http_server_requests_seconds_sum[5m])) / sum by (app, env) (rate(http_server_requests_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "P95 Latency (seconds) by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, app) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Request Rate (RPS) by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(env, app) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{env}}:{{app}}"
    }
   ]
  },
  {
   "title": "Max Latency (seconds) by Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(env, app) (http_server_requests_seconds_max)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}